[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/elad/elad2.pem

[web]
server1 ansible_host=100.26.145.209

[backend]
server2 ansible_host=34.229.0.191
server3 ansible_host=98.93.44.191